[package]
name = "anagrams"
version = "0.1.0"
authors = ["Noé Falzon"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
