#!/usr/bin/env lua

local bf = require "bf"
local hlbf = require "hlbf"

local args = {...}

local path = args[1]
if not path then
	error("Usage: ./interpreter source -hl")
end

local hl = args[2]
hl = hl == "-hl"

local fp = io.open(path, "r")
if not fp then
	error("Couldn't open file " .. path)
end

local src = fp:read "*a"
fp:close()

if hl then
	hlbf.run(src)
else
	bf.run(src)
end