#!/usr/bin/env lua

local t4 = require "t4"
local optbf = require "opt-bf"

local args = {...}

local debug = false
local run = false

local function printUsage()
	print("Usage: ./t4 [-debug] [-run] source1 [ source2 ... ]")
end

if #args < 1 then

end

local files = {}
for i,v in ipairs(args) do
	if v == "-debug" then
		debug = true
	elseif v == "-run" then
		run = true
	else
		table.insert(files, v)
	end
end


local src = t4.compile(files, debug)

if src then
	if run then
		
		if debug then
			print(src)
		end
		
		optbf.run(src)
	else
		print(src)
	end
end
