#!/usr/bin/env lua

local t4 = require "t4"
local bf = require "bf"

local args = {...}

local debug = false
local run = false

local files = {}
for i,v in ipairs(args) do
	if v == "-debug" then
		debug = true
	elseif v == "-run" then
		run = true
	else
		table.insert(files, v)
	end
end


local src = t4.compile(files)

if src then
	if run then
		bf.run(src)
	else
		print(src)
	end
end